import type { ScreenResult } from '../scorer/screen.js';

/**
 * Builds the plain-text Evidence Card that gets posted to modqueue.
 * No LLM needed — pure templated copy for v1.
 */
export function buildEvidenceCard(result: ScreenResult, contentUrl: string): string {
  if (!result.topMatch) return '';

  const { bannedUsername, score, explanation } = result.topMatch;

  const scoreBar = buildScoreBar(score);
  const topReasons = explanation
    .filter(e => e.contribution > 0)
    .slice(0, 5)
    .map(e => `• ${e.detail}`)
    .join('\n');

  const confidence =
    score >= 95 ? 'Very high' :
    score >= 80 ? 'High' :
    score >= 60 ? 'Moderate' : 'Low';

  return [
    `🚨 **ModSentry Alert** — ${confidence} confidence ban evasion`,
    ``,
    `**Match score: ${score}/100** ${scoreBar}`,
    `**Suspected alt of:** u/${bannedUsername}`,
    ``,
    `**Why this was flagged:**`,
    topReasons,
    ``,
    `**Mod actions:**`,
    `• Reply \`!ms-ban\` to confirm alt and ban`,
    `• Reply \`!ms-clear\` to clear and whitelist`,
    `• Reply \`!ms-watch\` to keep monitoring`,
    ``,
    `*This alert was generated by ModSentry. [View flagged content](${contentUrl})*`,
  ].join('\n');
}

function buildScoreBar(score: number): string {
  const filled = Math.round(score / 10);
  const empty = 10 - filled;
  return '█'.repeat(filled) + '░'.repeat(empty);
}

/**
 * Builds a short modmail message when an alt is confirmed and banned.
 */
export function buildBanModmail(
  bannedUsername: string,
  originalBanReason: string,
): string {
  return [
    `Your account has been banned from this subreddit.`,
    ``,
    `Our moderation tools detected that this account may be associated `,
    `with a previously banned user (u/${bannedUsername}).`,
    ``,
    `Original ban reason: ${originalBanReason}`,
    ``,
    `If you believe this is an error, please contact the mod team.`,
  ].join('\n');
}